apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-metrics-service-monitor
  namespace: monitoring #demo #monitoring
  labels:
    k8s-app: prometheus
    prometheus: k8s
    role: service-monitor
spec:
  namespaceSelector:
    matchNames:
      - default
      - demo
  selector:
    matchLabels:
      app: metrics-demo
  endpoints:
    - port: metrics
      interval: 30s
