apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-metrics-pod-monitor
  namespace: monitoring
  labels:
    k8s-app: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
      - ingress-nginx
  selector:
    matchLabels:
      app: ingress-ctrl-nginx-ingress
  podMetricsEndpoints:
    - port: prometheus
      interval: 30s
