{
 "title": "go-metrics-demo",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Votes rate[5m]",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "rate(votes_total[5m])" }
   ]
  },
  {
   "title": "Green votes total rate [5m]",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "rate(green_votes_total[5m])" }
   ]
  },
  {
   "title": "Yellow votes rate[5m]",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "rate(yellow_votes_total[5m])" }
   ]
  },
  {
   "title": "Red votes rate[5m]",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "rate(red_votes_total[5m])" }
   ]
  },
  {
   "title": "Green votes total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "green_votes_total" }
   ]
  },
  {
   "title": "Yellow votes total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "yellow_votes_total" }
   ]
  },
  {
   "title": "Red votes total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "red_votes_total" }
   ]
  },
  {
   "title": "Yellow votes rate [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(yellow_votes_total[5m])" }
   ]
  },
  {
   "title": "Votes total rate [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(votes_total[5m])" }
   ]
  },
  {
   "title": "Red votes rate [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(red_votes_total[5m])" }
   ]
  },
  {
   "title": "Green votes rate[5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(green_votes_total[5m])" }
   ]
  }
 ]
}