apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/components
resources:
  - dashboards/grafana-dashboardDefinitions.yaml
  # - resources/prometheus-rules.yaml
patchesStrategicMerge:
  - patches/prometheus-clusterRole.yaml  
  - patches/grafana-deployment.yaml
  - patches/prometheus-prometheus-names.yaml  