apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/components
resources:
  - dashboards/grafana-dashboardDefinitions.yaml
patchesStrategicMerge:
  - patches/prometheus-clusterRole.yaml  
  - patches/grafana-deployment.yaml